# Generated by Django 5.2 on 2025-05-07 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0003_alter_medico_genero_resultadoexame'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorpaciente',
            name='resultados_exames',
            field=models.ManyToManyField(related_name='exames_do_paciente', to='monitoramento.resultadoexame'),
        ),
        migrations.AlterField(
            model_name='resultadoexame',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_do_paciente', to='monitoramento.monitorpaciente'),
        ),
    ]
