# Generated by Django 5.2 on 2025-05-07 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0004_monitorpaciente_resultados_exames_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heartbeat',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batimentos_cardiacos', to='monitoramento.monitorpaciente'),
        ),
    ]
