# Generated by Django 5.2 on 2025-04-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('data_exame', models.DateField()),
                ('data_consulta', models.DateField()),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
